services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-seed:
    env_file:
      - .env
    build:
      context: ./mongo_seed
      dockerfile: Dockerfile
      args:
        - DATABASE_URI=$DATABASE_URI
    depends_on:
      - mongo

volumes:
  mongodb_data:
