services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-seed:
    env_file:
      - .env
    build:
      context: ./mongo_seed
      dockerfile: Dockerfile
      args:
        - DATABASE_URI=$DATABASE_URI
    depends_on:
      - mongo

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: ["start", "--all", "--config", "/etc/ngrok.yml"]
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"

volumes:
  mongodb_data:
